# Loaded by Chromium's build/config/ozone.gni via
# ozone_extra_path="//haiku_port/ozone_extra.gni".
ozone_external_platforms = [ "haiku" ]
ozone_external_platform_deps = [ "//haiku_port/ozone" ]
ozone_external_platform_test_deps = []
ozone_external_platform_integration_test_deps = []
ozone_external_platform_ui_test_support_deps = []
ozone_external_interactive_ui_tests_deps = []
